apps/hello/urls.py
from django.urls import path

from apps.hello import views

app_name = 'hello'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('edit-profile/', views.EditProfileDataView.as_view(), name='edit')
]

apps/requests/urls.py
from django.urls import path

from apps.requests import views

app_name = 'requests'

urlpatterns = [
    path('', views.LastTenRequestsView.as_view(), name='last_requests')
]

fortytwo_test_task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.hello.urls', namespace='hello')),
    path('requests/', include('apps.requests.urls', namespace='requests')),

    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

apps/hello/models.py
from PIL import Image
from django.db import models

from apps.hello.utils import resize_image


class ProfileModel(models.Model):
    """
    Model for profile info
    """
    name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    birthday_date = models.DateField()
    bio = models.TextField(verbose_name='Biography')
    profile_photo = models.ImageField(null=True, blank=True)

    email = models.EmailField(max_length=115)
    jabber = models.CharField(max_length=115)
    skype = models.CharField(max_length=115)

    other_contacts = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        """
        Resizing profile photo
        """
        # checking if the image needs to be resized
        if self.profile_photo:
            img = Image.open(self.profile_photo)
            if img.height > 200 or img.width > 200:
                self.profile_photo = resize_image((200, 200), self.profile_photo)
        super().save(*args, **kwargs)

apps/management/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


class DataBaseActionModel(models.Model):
    class Action(models.IntegerChoices):
        CREATION = 0
        DELETION = 1
        EDITING = 2

    app = models.CharField(max_length=115)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = GenericForeignKey()
    action = models.IntegerField(choices=Action.choices)

apps/requests/models.py
from django.conf import settings
from django.db import models


class RequestModel(models.Model):
    """
    Model for storing requests into db
    """
    url = models.URLField(max_length=300)
    method = models.CharField(max_length=10)
    encoding = models.CharField(max_length=10, null=True)
    content_type = models.CharField(max_length=50)
    priority = models.PositiveSmallIntegerField(default=1)

    timestamp = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        ordering = ('-timestamp',)
        get_latest_by = 'id'

apps/hello/forms.py
from django import forms
from apps.hello.models import ProfileModel


class EditProfileDataForm(forms.ModelForm):
    class Meta:
        model = ProfileModel
        fields = '__all__'
        widgets = {
            'birthday_date': forms.DateInput(attrs={'type': 'date'})
        }

apps/hello/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views.generic.base import View

from apps.hello.forms import EditProfileDataForm
from apps.hello.models import ProfileModel


class IndexView(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = ProfileModel.objects.first()
        return context


class EditProfileDataView(LoginRequiredMixin, View):

    def get(self, request):
        profile_instance = ProfileModel.objects.first()
        form = EditProfileDataForm(instance=profile_instance)
        context = {'form': form, 'profile': profile_instance}
        return render(request, 'edit_profile.html', context)

    def post(self, request):
        profile_instance = ProfileModel.objects.first()
        form = EditProfileDataForm(request.POST, instance=profile_instance)
        if form.is_valid():
            form.save()
            if not request.is_ajax():
                return redirect('hello:index')
            return JsonResponse({'success': True})
        else:
            errors = form.errors
            return JsonResponse({'success': False, 'errors': errors})

apps/management/views.py
# Create your views here.

apps/requests/views.py
from django.http import JsonResponse, Http404
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.views.generic.base import View

from apps.requests.models import RequestModel


class LastTenRequestsView(View):
    """
    This view will render page with last 10 requests
    and process ajax requests to get newer requests from db
    """

    def get(self, request):
        """
        Main method that process get requests, both ajax and common
        """
        if not request.is_ajax():
            try:
                latest_request_id = RequestModel.objects.filter(priority=1).latest().id
            except ObjectDoesNotExist:
                raise Http404
            qs = RequestModel.objects.filter(priority=1)[:10]
            context = {'requests': qs, 'latest_request_id': latest_request_id}
            return render(request, 'requests.html', context)
        else:
            # in get parameter 'id' we get id of the last request displayed
            # on page
            if request.GET.get('id'):
                # looking for newer requests
                # (with id grater then id we got from ajax)
                new_qs = RequestModel.objects.filter(id__gt=request.GET['id'], priority=1).order_by('timestamp')[:10]
                if new_qs.exists():
                    # serializing queryset
                    data = list(new_qs.values())
                    latest_request_id = data[-1]['id']
                    data = {
                        'requests': data, 'latest_request_id': latest_request_id
                    }
                    return JsonResponse(data)
                else:
                    return JsonResponse({'data': None})
            raise Http404

apps/hello/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block extra_head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
{% endblock extra_head %}

{% block title %}
    Edit page
{% endblock title %}

{% block content %}
<div class="container">
    <div class="title">
        <h1>42 Coffee Cups Test Assignment</h1>
        <a href="{% url 'hello:index' %}">Main page</a>
    </div>
    <div id="success" class="alert alert-primary" role="alert" hidden></div>
    <div id="fail" class="alert alert-danger" role="alert" hidden><ul></ul></div>

    <form id="profile_edit" method="post">
    {% csrf_token %}
	    <div class="row">

	        <div class="col-sm">
                <label for="">Name:</label>
	            {{ form.name }}<br>
	            <label for="last_name">Last name: </label>
	            {{ form.last_name }}<br>
	            <label for="b-day">Date of birth: </label>
	            {{ form.birthday_date }}<br>
	        </div>

	        <div class="col-sm">
	            <p>Contacts</p>
	            <label for="email">Email: </label>
	            {{ form.email }}<br>
                <label for="jabber">Jabber: </label>
	            {{ form.jabber }}<br>
	            <label for="skype">Skype: </label>
	            {{ form.skype }}<br>
	        </div>


	    </div>

	    <div class="row">
	    	<div class="col-sm">
                {% if profile.profile_photo %}
	    		<label for="photo">Photo:</label>
	            <img id="preview_img" src="/media/{{ profile.profile_photo }}" alt="Image">
                {% endif %}
	    	</div>

	    	<div class="col-sm">
	    		<div>
		            <label for="other_contacts">Other contacts: </label><br>
	            	{{ form.other_contacts }}<br>

	            </div>

	            <div>
		            <label for="bio">Bio: </label><br>
	            	{{ form.bio }}<br>
	            </div>
	        </div>

	    </div>

	    <div>
	    	<input style="margin-top: 10px" type="submit" name="" value="Submit">
	    	<input type="reset" name="" value="Reset to default">
	    </div>
	</form>
</div>
    <script src="{% static 'hello/js/script.js' %}"></script>
{% endblock content %}

apps/hello/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load admin_link_tag %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static "css/main.css" %}"/>
{% endblock extra_head %}

{% block content %}
<div class="container">
    <div class="title">
        <h1 class="title">42 Coffee Cups Test Assignment</h1>
        <a href="{% url 'hello:edit' %}">Edit</a>
        <a href="{% edit_link profile %}">(admin)</a> |
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <a href="{% url 'login' %}">Log In</a>
        {% endif %}

    </div>
    <div class="row">


        <div class="col-sm">
            <p>Name:</p>
            <p>{{ profile.name }}</p>
            <p>Last name:</p>
            <p>{{ profile.last_name }}</p>
            <p>Birthday:</p>
            <p>{{ profile.birthday_date }}</p>
        </div>

        <div class="col-sm">
            <p>Contacts</p>
            <p>Email: {{ profile.email }}</p>
            <p>Jabber: {{ profile.jabber }}</p>
            <p>Skype: {{ profile.skype }}</p>
        </div>


    </div>

    <div class="row">


        <div class="col-sm">
            {% if profile.profile_photo %}
            <p>Photo:</p>
            <img src="media/{{ profile.profile_photo }}">
            {% endif %}
        </div>

        <div class="col-sm">
            <div>
                <p>Other contacts:</p>
                <p>Telegram: {{ profile.telegram }}</p>
            </div>
            <div>
                <p>Bio:</p>
                <p class="bio">{{ profile.bio }}</p>
            </div>
        </div>


    </div>
    <hr>
    <div>
        <a href="{% url 'requests:last_requests' %}">Requests</a>
    </div>
</div>
{% endblock content %}

apps/requests/templates/requests.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock extra_head %}

{% block title %} Requests {% endblock title %}

{% block content %}
    <div clas="container">
		<div class="title">
			<h1>Requests</h1>
            <p hidden class="latest_req">{{ latest_request_id }}</p>
		</div>
		<div class="row">
			<div class="col-sm">
                {% for req in requests %}
				<div class="card">
				  <div class="card-header">
				    Method: {{ req.method }}
				  </div>
				  <div class="card-body">
				    <h5 class="card-title">URL: {{ req.url }}</h5>
				    <p class="card-text">
				    	content_type: {{ req.content_type }},
                        user: {{ req.user }}, encoding: {{ req.encoding }}
				    </p>
				    <p class="timestamp">Timestamp: {{ req.timestamp }}</p>
				  </div>
				</div>
                {% endfor %}
			</div>
		</div>
	</div>
    <script src="{% static 'requests/js/strftime.js' %}"></script>
    <script src="{% static 'requests/js/requests.js' %}"></script>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock title %}Site Name</title>

        <meta http-equiv="X-UA-Compatible" content="chrome=IE7" />

        <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/screen.css' %}" media="screen, projection"/>

        {% block extra_head %}{% endblock extra_head %}

    </head>
    <body id="{% block body_id %}{% endblock %}" class="{% block body_class %}{% endblock %}">
        {% block content %}{% endblock content %}
    </body>
</html>